---
- name: Install Nginx and Deploy Website
  hosts: webservers
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Nginx and Git
      apt:
        name:
          - nginx
          - git
        state: present

    - name: Start and enable Nginx
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Remove default nginx site
      file:
        path: /var/www/html
        state: absent

    - name: Clone repository
      git:
        repo: https://github.com/Balaji7774777/Application_Samples.git
        dest: /home/ubuntu/Application_Samples
        version: main
        force: yes

    - name: node2 copy application files
      copy:
        src: /home/ubuntu/Application_Samples/Static_Applications/portfolio
        dest: /var/www/portfolio
        remote_src: yes
      when: inventory_hostname == "node1"

    - name: node1 copy application files
      copy:
        src: /home/ubuntu/Application_Samples/Static_Applications_2/portfolio
        dest: /var/www/portfolio
        remote_src: yes
      when: inventory_hostname == "node2"
    
    - name: Set ownership and permissions
      file:
        path: /var/www/portfolio
        owner: www-data
        group: www-data
        mode: "0755"
        recurse: yes
  
    - name: Deploy nginx config
      copy:
        src: nginx.conf
        dest: /etc/nginx/conf.d/portfolio.conf
    
    - name: Test nginx config
      command: nginx -t

    - name: Restart nginx
      service:
        name: nginx
        state: restarted